apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebapp
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp
  labels:
    app: javawebapp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31000
    protocol: TCP
    name: http
  selector:
    app: javawebapp
